from document import window


class App(Component):
    state = {'count': 1}

    def onClick(self, event):
        self.setState({'count': self.state['count'] + 1})

    def render(self):
        # Modify the object generated by `props` to be a dictionary of
        # strings with explicit quotes

        return (
            <div>
                You've clicked the button {{ count }} times
                <button onClick={this.onClick}>Click Me</button>
            </div>
        )
